### ISSUE TITLE
Any chance of getting a Sequoia version?

### ISSUE THREAD

**Issue by bemfica** [VisualisationExpo/AquaLickX-Sonoma145Edition#1]
Self-explanatory title, if a bit early to be asking for that

**Comment by VisualisationExpo** [comment]
I'll take a look once I get Sequoia installed and see what tools exists/still work to make the theme. :)

I have a few applications I rely on to create the theme. Especially ThemeEngine has to work.

Thanks for asking.
😄

**Comment by wwessex** [comment]
Cool yes please

**Comment by MrGlitchWasTaken** [comment]
> I'll take a look once I get Sequoia installed and see what tools exists/still work to make the theme. :)
> 
> I have a few applications I rely on to create the theme. Especially ThemeEngine has to work.
> 
> Thanks for asking. 😄

any updates so far?

**Comment by VisualisationExpo** [comment]
I got a request to look into a Sonoma 14.7 issue. And while I’m working on that I’ll make the Sequoia theme.
This weekend I’ll gather. ThemeEngine appears to work fine.
I haven’t had the time to do much.

I hope this changes this weekend and a little while into next week.

Thanks for keeping me on my toes.


Sendt fra Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: MrGlitchWasTaken ***@***.***>
Sendt: Friday, October 11, 2024 9:22:31 PM
Til: VisualisationExpo/AquaLickX-Sonoma145Edition ***@***.***>
Cc: Allan Nyholm Nielsen ***@***.***>; Comment ***@***.***>
Emne: Re: [VisualisationExpo/AquaLickX-Sonoma145Edition] Any chance of getting a Sequoia version? (Issue #1)


I'll take a look once I get Sequoia installed and see what tools exists/still work to make the theme. :)

I have a few applications I rely on to create the theme. Especially ThemeEngine has to work.

Thanks for asking. 😄

any updates so far?

**Comment by VisualisationExpo** [comment]
![Screenshot 2024-10-14 at 20 30 33](https://github.com/user-attachments/assets/0766e4e0-1b70-438f-9604-9f03df77d82b)
[AquaLickX-LightModeSequoia1501.zip](https://github.com/user-attachments/files/17368165/AquaLickX-LightModeSequoia1501.zip)
Please test on your Mac @bemfica and @MrGlitchWasTaken @wwessex 

Only Light mode for now

**Comment by MrGlitchWasTaken** [comment]
> ![Screenshot 2024-10-14 at 20 30 33](https://private-user-images.githubusercontent.com/86615159/376351870-0766e4e0-1b70-438f-9604-9f03df77d82b.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NTQ5OTcsIm5iZiI6MTcyODk1NDY5NywicGF0aCI6Ii84NjYxNTE1OS8zNzYzNTE4NzAtMDc2NmU0ZTAtMWI3MC00MzhmLTk2MDQtOWYwM2RmNzdkODJiLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQwMTExMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDJlOWRmZmM0NDViNjRhZTY2ZGE3MmZlMWIwNTc4YjI4NGIwZDg1OGY3ZjM1M2M1NzU0NDJlZDE0ZmZmZjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6Mk6BCWqqCFEmOGFwFuuXiTnhk6cP6hSgy4u12nj550) [AquaLickX-LightModeSequoia1501.zip](https://github.com/user-attachments/files/17368165/AquaLickX-LightModeSequoia1501.zip) Please test on your Mac @bemfica and @MrGlitchWasTaken @wwessex
> 
> Only Light mode for now

are the installation instructions the same in the README for Sonoma version?

**Comment by MrGlitchWasTaken** [comment]
> ![Screenshot 2024-10-14 at 20 30 33](https://private-user-images.githubusercontent.com/86615159/376351870-0766e4e0-1b70-438f-9604-9f03df77d82b.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NTkxNzMsIm5iZiI6MTcyODk1ODg3MywicGF0aCI6Ii84NjYxNTE1OS8zNzYzNTE4NzAtMDc2NmU0ZTAtMWI3MC00MzhmLTk2MDQtOWYwM2RmNzdkODJiLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQwMjIxMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2M3MTJjYjc0ZWVkMzk4NjM1NDU1NTU4YTEwMTg3M2ZiYjIzOThkYzJjMzFhNjE1OWNiYmQ4ZjkwNGVhYTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZT4Bwrowfa6eGNMlR1dDbs2ihxCs2bouiV5DvjyOIBI) [AquaLickX-LightModeSequoia1501.zip](https://github.com/user-attachments/files/17368165/AquaLickX-LightModeSequoia1501.zip) Please test on your Mac @bemfica and @MrGlitchWasTaken @wwessex
> 
> Only Light mode for now

I actually used the instructions for sonoma and this actually worked (i just didnt follow part of the directions because there are no dark appearance car files)

**Comment by VisualisationExpo** [comment]
@MrGlitchWasTaken good that you followed the instructions as the ones for Sonoma and left the dark mode copying part out.
Once I got confirmation that it works on a different Mac than my own, I'll work on Dark mode for the Sequoia version. And you telling me that it works, gives me the go-ahead.

**Comment by VisualisationExpo** [comment]
Uploaded Sequoia version here https://github.com/VisualisationExpo/AquaLickX-SequoiaEdition

**Comment by iOS6Chatfield** [comment]
What's happening with Tahoe?

**Comment by VisualisationExpo** [comment]
> What's happening with Tahoe?

Nothing from me this time around :(

I don't have the time to update it, and I've generally lost interest in the project :)   

You could check out the fork from
[https://github.com/Vladimir-Moskalenko/AquaLickXV](url) and see if he has any updates in the pipeline for Tahoe.

I know he's updated it for Sequoia with some fixes, but for Tahoe? I don't know. 

Sorry mate.
